version: '3.8'

services:
  slave-worker:
    container_name: slave-worker
    build:
      context: ./slave-worker
      dockerfile: Dockerfile
    volumes:
      - shared_data:/shared

  master-worker:
    container_name: master-worker
    build:
      context: ./master-worker
      dockerfile: Dockerfile
    volumes:
      - shared_data:/shared

volumes:
  shared_data:
