version: '3.8'

services:
  master-worker:
    build:
      context: ./master-worker
      dockerfile: Dockerfile
    networks:
      - worker-network

  slave-worker:
    build:
      context: ./slave-worker
      dockerfile: Dockerfile
    networks:
      - worker-network

networks:
  worker-network:
